actor_lr: 3e-4
batch_size: 256
beta: 3.0
buffer_size: 10000000
checkpoints_path: checkpoints
device: cuda
discount: 0.99
env: null
eval_freq: 5000
group: iql-$env-multiseed-v0
iql_deterministic: false
iql_tau: 0.7
load_model: ''
max_timesteps: 250_000
n_episodes: 50
name: IQL
normalize: true
normalize_reward: true
# project: CORL-MetaWorld
qf_lr: 3e-4
seed: 0
tau: 0.005

vf_lr: 3e-4

data_quality: 5.0
trivial_reward: 0
use_reward_model: false
feedback_num: 1000
threshold: 0.5
data_aug: none
segment_size: 25
hidden_sizes: 128
ensemble_num: 3
ensemble_method: mean
q_budget: 1
feedback_type: RLT
model_type: BT
noise: 0.0
human: false
